language: node_js
node_js:
- node
sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_10c6a493b743_key -iv $encrypted_10c6a493b743_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $remote_address\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $username@$remote_address pwd
- mkdir work
- export PATH=$PATH:$PWD/work/
install:
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  -O $PWD/work/hugo.deb
- sudo dpkg -i $PWD/work/hugo.deb
- npm install
script:
- grunt build --verbose
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avu --delete  ./public/ $username@$remote_address:$filepath
  on:
    branch: master
